In [1]:
import pandas as pd
import numpy as np

1. Загрузите выборку Wine по адресу https://archive.ics.uci.edu/ml/machinelearning-databases/wine/wine.data

2. Извлеките из данных признаки и классы. Класс записан в первом
столбце (три варианта), признаки — в столбцах со второго по последний. Более подробно о сути признаков можно прочитать по адресу https://archive.ics.uci.edu/ml/datasets/Wine (см. также файл
wine.names, приложенный к заданию)


In [2]:
from sklearn.datasets import load_wine
wine=load_wine()

data=pd.DataFrame(data=np.c_[wine['data'],wine['target']],columns=wine['feature_names']+['target'])
data['target'] = data['target'] + 1
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0     1.0  
1                          3.40   1050.0     1.0  
2                          3.17   1185.0     1.0  
3                          3.45   1480.0     1.0  
4                          2.93    735.0     1.0

In [3]:
classes = data['target']
features = data.drop('target', axis=1)

3. Оценку качества необходимо провести методом кросс-валидации по
5 блокам (5-fold). Создайте генератор разбиений, который перемешивает выборку перед формированием блоков (shuffle=True). Для
3
воспроизводимости результата, создавайте генератор KFold с фиксированным параметром random_state=42. В качестве меры качества используйте долю верных ответов (accuracy).


In [4]:
from sklearn.model_selection import KFold

cv = KFold(n_splits=5, random_state=42, shuffle=True)

4. Найдите точность классификации на кросс-валидации для метода
k ближайших соседей (sklearn.neighbors.KNeighborsClassifier), при
k от 1 до 50. При каком k получилось оптимальное качество? Чему
оно равно (число в интервале от 0 до 1)? Данные результаты и
будут ответами на вопросы 1 и 2.


In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

scores = []
for k in range(1, 51):
    model = KNeighborsClassifier(k)
    scores.append(cross_val_score(model, features, classes, cv=cv, scoring='accuracy'))
scores

[array([0.77777778, 0.66666667, 0.72222222, 0.71428571, 0.77142857]),
 array([0.72222222, 0.63888889, 0.69444444, 0.57142857, 0.68571429]),
 array([0.80555556, 0.61111111, 0.63888889, 0.65714286, 0.82857143]),
 array([0.75      , 0.52777778, 0.61111111, 0.65714286, 0.74285714]),
 array([0.72222222, 0.61111111, 0.61111111, 0.68571429, 0.74285714]),
 array([0.72222222, 0.63888889, 0.63888889, 0.68571429, 0.68571429]),
 array([0.69444444, 0.58333333, 0.72222222, 0.68571429, 0.71428571]),
 array([0.72222222, 0.61111111, 0.66666667, 0.65714286, 0.74285714]),
 array([0.72222222, 0.63888889, 0.72222222, 0.68571429, 0.74285714]),
 array([0.72222222, 0.61111111, 0.63888889, 0.68571429, 0.74285714]),
 array([0.75      , 0.63888889, 0.66666667, 0.71428571, 0.74285714]),
 array([0.72222222, 0.66666667, 0.69444444, 0.68571429, 0.71428571]),
 array([0.72222222, 0.69444444, 0.66666667, 0.65714286, 0.71428571]),
 array([0.72222222, 0.66666667, 0.72222222, 0.6       , 0.68571429]),
 array([0.75      , 

In [6]:
res = pd.DataFrame(scores, index=np.arange(1, 51))
res = res.mean(axis=1)
res = res.sort_values(ascending=False)
print('k\tmean')
res.head()

k	mean


1     0.730476
34    0.724603
35    0.724603
48    0.719048
36    0.713492
dtype: float64

5. Произведите масштабирование признаков с помощью функции
sklearn.preprocessing.scale. Снова найдите оптимальное k на кроссвалидации.

In [7]:
from sklearn.preprocessing import scale

features = scale(features)

6. Какое значение k получилось оптимальным после приведения признаков к одному масштабу? Как изменилось значение качества?
Приведите ответы на вопросы 3 и 4.

In [8]:
scores = []
for k in range(1, 51):
    model = KNeighborsClassifier(k)
    scores.append(cross_val_score(model, features, classes, cv=cv, scoring='accuracy'))   
scores

[array([0.94444444, 0.94444444, 0.91666667, 0.97142857, 0.94285714]),
 array([0.94444444, 0.88888889, 0.91666667, 0.97142857, 0.94285714]),
 array([0.94444444, 0.94444444, 0.97222222, 0.97142857, 0.94285714]),
 array([0.94444444, 0.91666667, 0.94444444, 0.94285714, 0.94285714]),
 array([0.94444444, 0.94444444, 0.97222222, 0.91428571, 0.97142857]),
 array([0.94444444, 0.91666667, 0.97222222, 0.97142857, 0.94285714]),
 array([0.94444444, 0.91666667, 0.97222222, 0.94285714, 0.97142857]),
 array([0.94444444, 0.91666667, 0.97222222, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.97222222, 0.94285714, 1.        ]),
 array([0.94444444, 0.94444444, 0.97222222, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.94444444, 0.97142857, 1.        ]),
 array([0.97222222, 0.91666667, 0.94444444, 0.97142857, 0.97142857]),
 array([0.94444444, 0.94444444, 0.94444444, 0.91428571, 1.        ]),
 array([0.97222222, 0.94444444, 0.97222222, 0.97142857, 0.97142857]),
 array([0.97222222, 

точность увеличилась, узнаем при каком k будет лучшая точность

In [9]:
res_m = pd.DataFrame(scores, index=np.arange(1, 51))
res_m = res_m.mean(axis=1)
res_m = res_m.sort_values(ascending=False)
print('k\tmean')
res_m

k	mean


29    0.977619
16    0.972063
15    0.972063
17    0.966508
20    0.966508
22    0.966508
18    0.966508
28    0.966349
41    0.966349
33    0.966349
34    0.966349
14    0.966349
45    0.966349
43    0.966349
21    0.960952
11    0.960952
23    0.960952
32    0.960794
35    0.960794
26    0.960794
36    0.960794
30    0.960794
38    0.960794
39    0.960794
10    0.960794
9     0.960794
40    0.960794
42    0.960794
44    0.960635
50    0.960635
19    0.955397
31    0.955238
25    0.955238
24    0.955238
37    0.955238
12    0.955238
8     0.955238
27    0.955238
3     0.955079
49    0.955079
47    0.955079
48    0.949524
46    0.949524
7     0.949524
6     0.949524
13    0.949524
5     0.949365
1     0.943968
4     0.938254
2     0.932857
dtype: float64

In [11]:
difference = np.round(np.mean(res_m - res), 5)
print(f'прирост в точности после масштабирования: {difference}')

прирост в точности после масштабирования: 0.25927
