In [2]:
import numpy as np

1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер
памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы.
Затем загрузите его и выведите на экран

In [17]:
array = np.array([1, 7, 13, 105])
print(array.nbytes)

with open("arr_text.txt", "wt") as f:
    np.savetxt(f, array, fmt = "%i")

with open("arr_bin", "wb") as f:
    np.save(f, array)

with open('arr_text.txt', 'r') as f:
    print(f.read())

with open('arr_bin', 'rb') as f:
    a = np.load(f)
    print(a)


16
1
7
13
105

[  1   7  13 105]


##### 2. Три массива: из 10 нулей, 10 единиц, 10 пятерок

In [20]:
arr1 = np.zeros(10)
print(arr1)
arr2 = np.ones(10)
print(arr2)
arr3 = np.zeros(10)+5
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


##### 3. Массив последовательности четных целых чисел от 30 до 70.

In [22]:
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


##### 4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.

In [23]:
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


##### 5. Массив 3a[30]a[30] из 27 случайных чисел в диапазоне от 1 до 100.

In [24]:
arr = np.random.randint(1,100,size = [3,3,3])
print(arr)

[[[78 91 92]
  [73 69 39]
  [78  7 83]]

 [[93 53 16]
  [44 79 44]
  [38 23  5]]

 [[78  4 40]
  [65 95 15]
  [67 79 48]]]


##### 6. Массив 3х4, заполненной значениями от 30 до 41.

In [25]:
arr = np.arange(30,42).reshape([3,4])
print(arr)

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


##### 7. Массив 10a[10]0, в котором элементы на границах равны 1, а внутри 0

In [3]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


##### 8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

In [4]:
arr = np.diag([1, 2, 3, 4, 5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


##### 9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на
главной диагонали.

In [5]:
arr = np.zeros((4, 4))
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


##### 10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата

In [8]:
arr = np.arange(np.datetime64('2017-03-01'), np.datetime64('2017-04-01'))
print(arr)

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


##### 1. Дано два массива. Получите массив, состоящий из их общих элементов.

In [10]:
a = np.array([2, 4, 7, 1, 4])
b = np.array([7, 2, 9, 0, 5])
c = np.intersect1d(a, b)
print(c)

[2 7]


##### 2. Дан массив. Получите массив его уникальных элементов.


In [11]:
arr=np.unique([1,1,1,1,1,1,1,2,2,2,3,3,4,4,5,5,6])
print(arr)

[1 2 3 4 5 6]


##### 3. Дан массив. Получите два массива: его уникальные элементы и их частоты

In [14]:
arr,counts=np.unique([1,1,1,1,1,1,1,2,2,2,3,3,4,4,5,5,6],return_counts=True)
print(arr)
print(counts)

[1 2 3 4 5 6]
[7 3 2 2 2 1]


##### 4. Дан массив. Получите массив путем повторения данного

In [15]:
arr=np.tile([1,2,3], 3)
print(arr)

[1 2 3 1 2 3 1 2 3]


##### 5. Дан массив, в котором имеются значения nan. Получите массив, удалив все значения nan.

In [19]:
arr= np.array([200, 300, np.nan, np.nan, np.nan, 700])
b = arr[np.logical_not(np.isnan(arr))]
print(b)

[200. 300. 700.]


##### 6. Дан массив. Получите массив его k наименьших значений

In [20]:
arr = np.sort(np.array([23, 12, 1, 3, 4, 5, 6]))
k=3
print(arr[:3])

[1 3 4]


##### 7. Дан массив и некоторое число. Найдите ближайший по значению к числу элемент массива.

In [28]:
arr = np.array([23, 12, 1, 3, 4, 5, 6,2.5])
v = 2.6
n = arr[np.abs(arr - v).argmin()]
print(n)

2.5


##### 8. Дано два массива со строками. Получите массив при помощи поэлементного объединения.

In [32]:
a[10] = np.array(['Python', 'PHP'])
a[20] = np.array([' Java', ' C++'])
new_array = np.char.add(a[10], a[20])
print(new_array)

['Python Java' 'PHP C++']


##### 9. Дан массив строк. Получите массив с частотой встречаемости буквы «P».

In [37]:
arr = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
print(np.char.count(arr,"P"))

[1 2 0 0 0]


##### 10. Найдите корни следующих полиномов:

a) x^2 - 4х + 7

b) x^4 - 11х^3 + 9х^2 + 11х - 10


In [40]:
a = np.poly1d([1, -4, 7])
b = np.poly1d([1, -11, 9, 11, -10])
print(a)
print(a.r)
print()
print(b)
print(b.r)

   2
1 x - 4 x + 7
[2.+1.73205081j 2.-1.73205081j]

   4      3     2
1 x - 11 x + 9 x + 11 x - 10
[10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]


![alt text](num3.png "Title")

In [44]:
a11 = int(input("a11->"))
a12 = int(input("a12->"))
a21 = int(input("a21->"))
a22 = int(input("a22->"))

r1 = int(input("r1->"))
r2 = int(input("r2->"))

arr = np.array([[a11,a12],[a21,a22]])
arr2 = np.array([r1,r2])

if np.linalg.det(arr) == 0:
    print("нет решений")
else:
    print(np.linalg.solve(arr,arr2))


-1.0000000000000004
[-1.  1.]
