In [1]:
import numpy as np

1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер
памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы.
Затем загрузите его и выведите на экран

In [17]:
array = np.array([1, 7, 13, 105])
print(array.nbytes)

with open("arr_text.txt", "wt") as f:
    np.savetxt(f, array, fmt = "%i")

with open("arr_bin", "wb") as f:
    np.save(f, array)

with open('arr_text.txt', 'r') as f:
    print(f.read())

with open('arr_bin', 'rb') as f:
    a = np.load(f)
    print(a)


16
1
7
13
105

[  1   7  13 105]


2. Три массива: из 10 нулей, 10 единиц, 10 пятерок

In [20]:
arr1 = np.zeros(10)
print(arr1)
arr2 = np.ones(10)
print(arr2)
arr3 = np.zeros(10)+5
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


3. Массив последовательности четных целых чисел от 30 до 70.

In [22]:
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.

In [23]:
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.

In [24]:
arr = np.random.randint(1,100,size = [3,3,3])
print(arr)

[[[78 91 92]
  [73 69 39]
  [78  7 83]]

 [[93 53 16]
  [44 79 44]
  [38 23  5]]

 [[78  4 40]
  [65 95 15]
  [67 79 48]]]


6. Массив 3х4, заполненной значениями от 30 до 41.

In [25]:
arr = np.arange(30,42).reshape([3,4])
print(arr)

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0

In [ ]:
arr = np.zeros()

8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

In [29]:
arr = np.zeros([5,5]).diagonal(1)+1
print(arr)

[1. 1. 1. 1.]


9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на
главной диагонали.

In [ ]:
arr = np.

10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата

In [ ]:
arr = np.